credentials:
  usernames:
    admin:
      email: 2022mt12028@wilp.bits-pilani.ac.in
      name: Admin
      password: '$2b$12$pUIcjMYki0Xl7xjsOXjgE.26/CE.m/u8T0sFbhoYkGAZE8IJ.ieV.'
cookie:
  expiry_days: 30
  key: dda-pharmacy-cookie-key
  name: dda-pharmacy-cookie
preauthorized:
  emails:
  - melsby@gmail.com